config/routes.rb
Rails.application.routes.draw do

  resources :enqueues
  get 'index' => 'home#index'
  root 'home#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy', as: 'logout'


  resources :users
  resources :session
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enqueue.rb
class Enqueue < ApplicationRecord
  belongs_to :user
  has_many :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :enqueue
  has_many :question
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :enqueue
    has_many :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    private

        def current_user
            @current_user  = User.find(session[:user_id]) if session[:user_id]
        end
        helper_method :current_user
end

app/controllers/enqueues_controller.rb
class EnqueuesController < ApplicationController
  before_action :set_enqueue, only: [:show, :edit, :update, :destroy]

  # GET /enqueues
  # GET /enqueues.json
  def index
    @enqueues = Enqueue.all
  end

  # GET /enqueues/1
  # GET /enqueues/1.json
  def show
  end

  # GET /enqueues/new
  def new
    @enqueue = Enqueue.new
  end

  # GET /enqueues/1/edit
  def edit
  end

  # POST /enqueues
  # POST /enqueues.json
  def create
    @enqueue = Enqueue.new(enqueue_params)

    respond_to do |format|
      if @enqueue.save
        format.html { redirect_to @enqueue, notice: 'Enqueue was successfully created.' }
        format.json { render :show, status: :created, location: @enqueue }
      else
        format.html { render :new }
        format.json { render json: @enqueue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enqueues/1
  # PATCH/PUT /enqueues/1.json
  def update
    respond_to do |format|
      if @enqueue.update(enqueue_params)
        format.html { redirect_to @enqueue, notice: 'Enqueue was successfully updated.' }
        format.json { render :show, status: :ok, location: @enqueue }
      else
        format.html { render :edit }
        format.json { render json: @enqueue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enqueues/1
  # DELETE /enqueues/1.json
  def destroy
    @enqueue.destroy
    respond_to do |format|
      format.html { redirect_to enqueues_url, notice: 'Enqueue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enqueue
      @enqueue = Enqueue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enqueue_params
      params.require(:enqueue).permit(:title, :text, :type, :category, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Login Realizado com Sucesso!"
    else
      flash.now.alert = "Email ou Password Inválido"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logout realizado com sucesso"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user =User.new(allowed_params)
        if @user.save
            redirect_to root_url, notice: "Obrigado por se Cadastrar"
        else
            render "new"
        end
    end

    private
    def allowed_params
        params.require(:user).permit(:name, :sex, :email, :password, :password_confirmation)
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enqueues_helper.rb
module EnqueuesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enqueues/_form.html.erb
<div class="container">
<%= form_with(model: enqueue, local: true) do |form| %>
  <% if enqueue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enqueue.errors.count, "error") %> prohibited this enqueue from being saved:</h2>

      <ul>
      <% enqueue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   
                    <div class="col s12 m8">
                    
                        <div class="row">
                            <div class="input-field col s12">
                              <%= form.label :título %>
                              <%= form.text_field :title %>
                            </div>
                        </div>

                        <div class="row">
                          <div class="input-field col s6">
                            <%= form.label :Tipo %>
                            <%= form.text_field :tipo_enquete %>
                          </div>
                          <div class="input-field col s6">
                            <%= form.label :Categoria %>
                            <%= form.text_field :category %>
                          </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                              
                              <%= form.text_area :text, :class => 'editor' %>
                            </div>
                        </div>

                        


    <%= form.hidden_field :user_id, :value => @current_user %>
  
  <div class="actions center-align">
    <%= form.submit 'Criar Enquete', :class => "btn waves-effect waves-light"%>
  </div>
  </div>
  
<% end %>
</div>

app/views/enqueues/edit.html.erb
<h1>Editing Enqueue</h1>

<%= render 'form', enqueue: @enqueue %>

<%= link_to 'Show', @enqueue %> |
<%= link_to 'Back', enqueues_path %>

app/views/enqueues/index.html.erb
<%= render partial: "/layouts/navbar"%>
<div class="container">

<p id="notice"><%= notice %></p>

<h2>Todas as Enquetes</h2>

<% @enqueues.each do |enqueue| %>
    <div class="row">
        <div class="col s12 m4 grey lighten-4">
        </div>
        <div class="col s12 m8">
          <div class="row">
            <h4><%=enqueue.title%></h4>
          </div>
          <div class="row">
            <h5><%= enqueue.user.nome%></h5> - <p><%= enqueue.created_at.to_date %></p>
          </div>
          <div class="row">
            <p class="grey-text">
              <%= enqueue.text.truncate(120, omission: '... Ler Mais')%>
            </p>
          </div>
          <%= link_to 'Show', enqueue %>
          <% if @current_user == enqueue.user.id %>
            <%= link_to 'Editar', edit_enqueue_path(enqueue) %>
            <%= link_to 'Excluir', enqueue, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
    </div>
 <% end %>
  

<%= link_to 'New Enqueue', new_enqueue_path %>
</div>

app/views/enqueues/new.html.erb
<h1>New Enqueue</h1>

<%= render 'form', enqueue: @enqueue %>

<%= link_to 'Back', enqueues_path %>

app/views/enqueues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @enqueue.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @enqueue.text %>
</p>

<p>
  <strong>Type:</strong>
  <%= @enqueue.type %>
</p>

<p>
  <strong>Category:</strong>
  <%= @enqueue.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @enqueue.user %>
</p>

<%= link_to 'Edit', edit_enqueue_path(@enqueue) %> |
<%= link_to 'Back', enqueues_path %>

app/views/home/index.html.erb
<%= render partial: "/layouts/navbar"%>

app/views/layouts/_navbar.html.erb
<% if current_user %>
<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
    
        <li><a href="<%= logout_path %>" alt="Sair"><i class="material-icons left">exit_to_app</i> Sair</a></li>
      </ul>
    </div>
  </nav>
<% else %>
   <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%= signup_path %>" alt="Login"><i class="material-icons left">person_add</i> Cadastrar-se</a></li>
        <li><a href="<%= login_path %>" alt="Login"><i class="material-icons left">account_circle</i> Login</a></li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enqueues</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<div class="container">
    <div class="card">
        <div class="card-tabs">
        <ul class="tabs tabs-fixed-width">
            <li class="tab"><a class="active" href="#login">Login</a></li>
            <li class="tab"><a  href="<%= signup_path%>">Cadastro</a></li>
        </ul>
        </div>
        <div class="card-content grey lighten-5">
        <div id="login">
        
            <div class="center-align">
                <h3>Login</h3>
                <p>Poxa vida a gente já tava com saudades!!!</p>
            </div>

            <%= form_tag login_path do %>
            <div class="container">
                    <div class="col s12 m8">
                    
                        <div class="row">
                            <div class="input-field col s12">
                            <%= label_tag :email%>
                            <%= text_field_tag :email, params[:email]%>
                        </div></div>

                        <div class="row">
                            <div class="input-field col s12">
                            <%= label_tag :senha%>
                            <%= password_field_tag :password%>
                        </div>
                        </div>

                        <div class="actions center-align">
                            <%= submit_tag "Entrar", :class => "btn waves-effect waves-light" %>
                        </div>
                    </div>
                </div>
            <%end%>
           
        </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="card">
        <div class="card-tabs">
        <ul class="tabs tabs-fixed-width">
            <li class="tab"><a href="<%= login_path %>">Login</a></li>
            <li class="tab"><a class="active" href="#cadastro">Cadastro</a></li>
        </ul>
        </div>
        <div class="card-content grey lighten-5">
        <div id="cadastro">
        
            <div class="center-align">
                <h3>Cadastre-se</h3>
                <p>Ora ora, quem temos por aqui... perde tempo não bora cadastrar logo!!!</p>
            </div>

            <%= form_for @user do |f|%>
                <% if @user.errors.any?%>
                    <div class="container">
                        <div class="col s12 m8">
                            <ul class="collection with-header">
                                <li class="collection-header"><b>Ops! algo de errado não está certo</b></li>
                                <% @user.errors.full_messages.each do |message|%>
                                    <li class="collection-item"><div> <%= message %><a class="secondary-content"><i class="material-icons">report_problem</i></a></div></li>
                                <%end%>
                            </ul>
                        </div>
                    </div>
                <%end%>
            
            <div class="container">
                    <div class="row">
                            <div class="input-field col s12">
                            <%= f.label :nome%>
                            <%= f.text_field :name%>
                        </div></div>

                        <div class="row">
                            <div class="input-field col s12">
                            <%= f.label :email%>
                            <%= f.text_field :email%>
                        </div></div>

                        <div class="row">
                            <div class="input-field col s12">
                                
                                <%= f.select :sex, ['Masculino','Feminino','Intersex'] %>
                                <%= f.label :sexo%>
                            </div>
                        </div
                        >
                        <div class="row">
                            <div class="input-field col s12">
                            <%= f.label :senha%>
                            <%= f.password_field :password%>
                        </div></div>

                        <div class="row">
                            <div class="input-field col s12">
                            <%= f.label :'confirme a senha'%>
                            <%= f.password_field :password_confirmation%>
                        </div></div>

                        <div class="actions center-align">
                            <%= f.submit  'Cadastrar', :class=>"btn waves-effect waves-light"%>
                        </div>
                    </div>
                </div>
            <%end%>
        
        </div>
        </div>
    </div>
</div>